apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: cms-fraud
type: Opaque
stringData:
  POSTGRES_DB: cms_fraud
  POSTGRES_USER: cms
  POSTGRES_PASSWORD: cms_local_dev
  DATABASE_URL: postgresql://cms:cms_local_dev@postgres:5432/cms_fraud
---
apiVersion: v1
kind: Secret
metadata:
  name: neo4j-credentials
  namespace: cms-fraud
type: Opaque
stringData:
  NEO4J_AUTH: neo4j/cms_graph_dev
  NEO4J_PASSWORD: cms_graph_dev
  NEO4J_URI: bolt://neo4j:7687
